# Generated by Django 6.1 on 2026-08-21 07:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0002_tax"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tax",
            options={"verbose_name_plural": "tax"},
        ),
    ]
