# Generated by Django 6.1 on 2026-08-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_remove_userprofile_address_line_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
