# Generated by Django 5.2.13 on 2026-08-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0003_alter_item_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category_name",
            field=models.CharField(max_length=50),
        ),
    ]
