# Generated by Django 6.1 on 2026-08-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
        ("vendor", "0006_alter_openinghour_from_hour_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="vendors",
            field=models.ManyToManyField(blank=True, to="vendor.vendor"),
        ),
    ]
